#!/bin/bash
echo "Sorry, you are going to have to type the password multiple times"
echo "And before you ask why I didn't do it another way, like using 'expect' or 'sshpass', its because this is a one time thing, and those packages aren't always readily avaliable to everyone. They weren't even installed by default on my version of Ubuntu."

bbb=bbb1
addr=128.174.163.125

scp BB-ADC-00A0.dts $bbb@$addr:~/
scp BB-DCAN1-00A0.dts $bbb@$addr:~/
scp BB-GPIO-01-00A0.dts $bbb@$addr:~/
scp BB-PRU-01-00A0.dts $bbb@$addr:~/
scp BB-PWM1-00A0.dts $bbb@$addr:~/
scp w1.dts $bbb@$addr:~/
scp pru_encoder/Debug/pru_encoder.out $bbb@$addr:~/
scp halt/Debug/halt.out $bbb@$addr:~/
scp initPRU $bbb@$addr:~/
scp setupOverlay $bbb@$addr:~/
