#!/bin/bash

echo "Compiling the overlay from .dts to .dtbo"
 
dtc -O dtb -o BB-SPI-M-01-00A0.dtbo -b 0 -@ BB-SPI-M-01-00A0.dts

cp BB-SPI-M-01-00A0.dtbo /lib/firmware

cat /sys/devices/platform/bone_capemgr/slots

echo BB-SPI-M-01 > /sys/devices/platform/bone_capemgr/slots

