#!/bin/bash

echo "Copying firmware to /lib/firmware/am335x_pru0_fw"
cp halt.out        /lib/firmware/am335x_pru0_fw

echo "Copying firmware to /lib/firmware/am335x_pru1_fw"
cp pru_encoder.out /lib/firmware/am335x_pru1_fw

echo "Rebooting pru core 0"
echo 'stop' > /sys/class/remoteproc/remoteproc1/state
echo 'am335x_pru0_fw' > /sys/class/remoteproc/remoteproc1/firmware
echo 'start' > /sys/class/remoteproc/remoteproc1/state
echo "pru core 0 is now loaded"

echo "Rebooting pru core 1"
echo 'stop' > /sys/class/remoteproc/remoteproc2/state
echo 'am335x_pru1_fw' > /sys/class/remoteproc/remoteproc2/firmware
echo 'start' > /sys/class/remoteproc/remoteproc2/state
echo "pru core 1 is now loaded"



