#!/bin/bash

echo "Compiling the overlays from .dts to .dtbo"
 
dtc -O dtb -o BB-SPI-M-01-00A0.dtbo -b 0 -@ BB-SPI-M-01-00A0.dts
dtc -O dtb -o bspm_P9_12_27-00A0.dtbo -b 0 -@ bspm_P9_12_27-00A0.dts
dtc -O dtb -o bspm_P9_15_f-00A0.dtbo -b 0 -@ bspm_P9_15_f-00A0.dts
dtc -O dtb -o BB-DCAN1-00A0.dtbo -b 0 -@ BB-DCAN1-00A0.dts

cp BB-SPI-M-01-00A0.dtbo /lib/firmware
cp bspm_P9_12_27-00A0.dtbo /lib/firmware
cp bspm_P9_15_f-00A0.dtbo  /lib/firmware
cp BB-DCAN1-00A0.dtbo /lib/firmware

echo "Before"
cat /sys/devices/platform/bone_capemgr/slots

echo BB-SPI-M-01 > /sys/devices/platform/bone_capemgr/slots
echo bspm_P9_12_27 > /sys/devices/platform/bone_capemgr/slots
echo bspm_P9_15_f  > /sys/devices/platform/bone_capemgr/slots
echo BB-DCAN1 > /sys/devices/platform/bone_capemgr/slots

echo "After"
cat /sys/devices/platform/bone_capemgr/slots

modprobe can
modprobe can-dev
modprobe can-raw

ifconfig | grep can0 > /dev/null
while [ $? -ne 0 ] ; do
  echo "Sleeping one, can0 not present"
  sleep 1
  ifconfig | grep can0 > /dev/null
done

ip link set can0 up type can bitrate 500000
ifconfig can0 up

exit 0
