#!/bin/bash
echo 66 > /sys/class/gpio/export
echo "in" > /sys/class/gpio/gpio66/direction
echo 26 > /sys/class/gpio/export
echo "in" > /sys/class/gpio/gpio26/direction
echo 46 > /sys/class/gpio/export
echo "in" > /sys/class/gpio/gpio46/direction
echo 65 > /sys/class/gpio/export
echo "in" > /sys/class/gpio/gpio65/direction
echo 61 > /sys/class/gpio/export
echo "in" > /sys/class/gpio/gpio61/direction
echo 45 > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio45/direction
echo 68 > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio68/direction
echo 69 > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio69/direction
