#!/bin/bash
echo 68 > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio68/direction
echo 69 > /sys/class/gpio/export
echo "out" > /sys/class/gpio69/direction
echo 13 > /sys/class/gpio/export
echo "out" > /sys/class/gpio13/direction
