#!/bin/bash

echo "Compiling the overlays from .dts to .dtbo"
dtc -O dtb -o BB-DCAN1-00A0.dtbo -b 0 -@ BB-DCAN1-00A0.dts
dtc -O dtb -o BB-ADC-00A0.dtbo -b 0 -@ BB-ADC-00A0.dts
dtc -O dtb -o BB-PWM1-00A0.dtbo -b 0 -@ BB-PWM1-00A0.dts
dtc -O dtb -o BB-PRU-01-00A0.dtbo -b 0 -@ BB-PRU-01-00A0.dts
dtc -O dtb -o BB-GPIO-01-00A0.dtbo -b 0 -@ BB-GPIO-01-00A0.dts
dtc -O dtb -o w1-00A0.dtbo -b 0 -@ w1.dts

echo "Copying the overlays into /lib/firmware"
cp BB-DCAN1-00A0.dtbo /lib/firmware
cp BB-ADC-00A0.dtbo /lib/firmware
cp BB-PWM1-00A0.dtbo /lib/firmware
cp BB-PRU-01-00A0.dtbo /lib/firmware
cp BB-GPIO-01-00A0.dtbo /lib/firmware
cp w1-00A0.dtbo /lib/firmware

rm *.dtbo

echo "Complete. Remember to include these overlays in the /boot/uEnv.txt file."
echo "Once included in the uEnv.txt file, they will automatically be loaded"

exit 0
