% -------------------------------------------------------------------
%  Generated by MATLAB on 31-Oct-2018 02:22:05
%  MATLAB version: 9.5.0.944444 (R2018b)
% -------------------------------------------------------------------
saveVarsMat = load('profile_data.mat');

AccelerationDistance = 1003.7866639228318;

AccelerationDistanceVec = 1003.7866639228318;

AccelerationRunTime = 13.219999999999763;

BrakingForce = 7579.2414898391735;

BrakingForceVec = 7579.2414898391735;

ControllerInputPowerEmrax = 0;

ControllerInputPowerTP100 = 0;

EmraxBatteryAH = 22;

EmraxBatteryMaxPower = 100;

EmraxBatteryResistance = 0.04;

EmraxBatteryVoltage = 125;

EmraxBatteryWeight = 20;

EmraxControllerEfficiency = 0.95;

EmraxCurrent = 0;

EmraxGearIdx = 4;

EmraxMaxRPM = 4400;

EmraxPeakTorque = 240;

EmraxPower = 50;

EmraxRPM = 4400.5194386230951;

EmraxWeight = 12;

EmraxWheelRPM = 17602.07775449238;

EmsisoWeight = 4.9;

MechPowerEmrax = 0;

MechPowerTP100 = 0;

MotorInputPowerEmrax = 0;

MotorInputPowerTP100 = 0;

Plot_things = false;

TP100AvgBatteryAH = 8.25;

TP100AvgBatteryMaxPower = 25;

TP100AvgBatteryResistance = 0.03;

TP100AvgBatteryWeight = 5;

TP100AvgWeight = 4.666666666666667;

TP100BatteryVoltage = 85;

TP100ControllerEfficiency = 0.95;

TP100Current = 0;

TP100GearIdx = 0.7;

TP100GearRatio = 1;

TP100MaxRPM = 25000;

TP100Num = 6;

TP100PeakTorque = 9.75;

TP100Power = 20;

TP100RPM = 25145.825363560543;

TP100WheelRPM = 17602.07775449238;

TopSpeed = 138.569108298959;

TopSpeedVec = 138.569108298959;

TorqueEmrax = 0;

TorqueEmraxWheel = 0;

TorqueTP100 = 0;

TorqueTP100Wheel = 0;

TractionForceEmrax = 0;

TractionForceTP100 = 0;

a = 0;

acceleration = saveVarsMat.acceleration; % <1x1462 double> too many elements

controllerInputPowerEmrax = saveVarsMat.controllerInputPowerEmrax; % <1x1462 double> too many elements

controllerInputPowerTP100 = saveVarsMat.controllerInputPowerTP100; % <1x1462 double> too many elements

d = 1200.1100038220773;

distance = saveVarsMat.distance; % <1x1462 double> too many elements

dt = 0.01;

em_r = 0.04;

emraxBatteryVoltage = 124.92292006550309;

emraxCurrent = saveVarsMat.emraxCurrent; % <1x1462 double> too many elements

emraxResistanceVec = 0.04;

emraxVoltage = saveVarsMat.emraxVoltage; % <1x1462 double> too many elements

emrax_battery_max_power = 100;

emrax_mech_power = 50;

g = 5.0105387803331229;

gVec = 5.0105387803331229;

gearVecEmrax = 4;

gearVecTp100 = 0.7;

gear_emrax = 4;

gear_tp100 = 0.7;

gtotal = saveVarsMat.gtotal; % <1x1462 double> too many elements

heatEmissio = 31984.447662970149;

heatEmrax = 52967.026100641531;

heatEmraxBattery = 123167.31691375315;

heatTP100 = 40503.00626941926;

heatTP100Battery = 20908.151193048248;

heatTP100Controller = 10658.68586037332;

i = 1323;

k = 1;

mass = 154.9;

maxG = 5;

maxTopSpeed = 138.569108298959;

mechPowerEmrax = saveVarsMat.mechPowerEmrax; % <1x1462 double> too many elements

mechPowerTP100 = saveVarsMat.mechPowerTP100; % <1x1462 double> too many elements

motorInputPowerEmrax = saveVarsMat.motorInputPowerEmrax; % <1x1462 double> too many elements

motorInputPowerTP100 = saveVarsMat.motorInputPowerTP100; % <1x1462 double> too many elements

p_opts = 1;

radiusEmrax = 0.0762;

radiusTP100 = 0.0762;

runlength = 1200;

t = 14.619999999999733;

time = saveVarsMat.time; % <1x1462 double> too many elements

tp100BatteryVoltage = 84.9072759483445;

tp100Current = saveVarsMat.tp100Current; % <1x1462 double> too many elements

tp100Voltage = saveVarsMat.tp100Voltage; % <1x1462 double> too many elements

v = 140.45833773003113;

velocity = saveVarsMat.velocity; % <1x1462 double> too many elements

clear saveVarsMat;
