# Generated by Django 2.1.3 on 2018-11-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recv_time', models.DateTimeField(verbose_name='Received')),
                ('state', models.CharField(max_length=200)),
                ('position', models.FloatField(default=0.0)),
                ('velocity', models.FloatField(default=0.0)),
                ('acceleration', models.FloatField(default=0.0)),
                ('cpu_temp', models.FloatField(default=0.0)),
            ],
        ),
    ]
