# Generated by Django 2.1.3 on 2018-11-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='recv_time',
            field=models.IntegerField(default=0.0),
        ),
    ]
