# Generated by Django 2.1.3 on 2018-11-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20181126_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='acceleration',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='cpu_temp',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='position',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='velocity',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
