# Generated by Django 2.1.3 on 2019-01-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPacket',
            fields=[
                ('date_time', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('velocity', models.IntegerField(null=True)),
                ('acceleration', models.IntegerField(null=True)),
                ('position', models.IntegerField(null=True)),
            ],
        ),
    ]
