# Generated by Django 2.2.1 on 2019-05-04 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podconnect', '0002_auto_20190503_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candata',
            old_name='fail_safe_sate',
            new_name='fail_safe_state',
        ),
        migrations.RenameField(
            model_name='candata',
            old_name='low_cell_voltge',
            new_name='low_cell_voltage',
        ),
    ]
