# Generated by Django 2.1.3 on 2019-07-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podconnect', '0005_auto_20190715_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='motiondata',
            name='brake_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motiondata',
            name='motor_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motiondata',
            name='motor_target_torque',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motiondata',
            name='relay_state_buff_0',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='motiondata',
            name='relay_state_buff_1',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='motiondata',
            name='relay_state_buff_2',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='motiondata',
            name='relay_state_buff_3',
            field=models.CharField(default='', max_length=1),
        ),
    ]
