# Generated by Django 2.1.3 on 2019-07-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podconnect', '0006_auto_20190716_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motiondata',
            name='relay_state_buff_0',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='motiondata',
            name='relay_state_buff_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='motiondata',
            name='relay_state_buff_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='motiondata',
            name='relay_state_buff_3',
            field=models.IntegerField(default=0),
        ),
    ]
