# Generated by Django 2.1.3 on 2019-07-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podconnect', '0008_auto_20190717_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='motiondata',
            name='a_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motiondata',
            name='a_timeout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motiondata',
            name='b_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motiondata',
            name='b_timeout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motiondata',
            name='c_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motiondata',
            name='c_timeout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motiondata',
            name='p_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motiondata',
            name='p_timeout',
            field=models.IntegerField(default=0),
        ),
    ]
